# Set update schedule for GitHub Actions

version: 2

registries:
  github-textshuttle:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.PYPAE_GITHUB_ACCESS_TOKEN}}

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    registries:
      - github-textshuttle
    insecure-external-code-execution: allow
